// You are given a one dimensional array that may contain both positive and negative integers, find the sum of contiguous subarray of numbers which has the largest sum. For example, if the given array is {-2, -5, 6, -2, -3, 1, 5, -6}, then the maximum subarray sum is 7.

// Input Format
// The first line consists of number of test cases T. Each test case consists of two lines.
// The first line of each testcase contains a single integer N denoting the number of elements for the array A.
// The second line of each testcase contains N space separated integers denoting the elements of the array.

// Constraints
// 1 <= N <= 100000

// 1 <= t <= 20

// -100000000 <= A[i] <= 100000000

// Output Format
// Output a single integer denoting the maximum subarray sum for each testcase in a new line.

// Sample Input
// 2
// 4
// 1 2 3 4
// 3
// -10 5 10
// Sample Output
// 10
// 15
// Explanation
// For the first testcase, maximum subarray sum is generated by the entire array - 1+2+3+4 = 10
// For the second testcase , maximum subarray sum is generated by the subarray {5,10} - 5+10 = 15

#include <iostream>

using namespace std;

int best_method(int *a, int n)
{
    int max_sum_here = 0;
    int max_sum_sofar = 0;
    for (int i = 0; i < n; i++)
    {
        max_sum_here += a[i];
        if (max_sum_sofar < max_sum_here)
        {
            max_sum_sofar = max_sum_here;
        }
        if (max_sum_here < 0)
        {
            max_sum_here = 0;
        }
    }
    return max_sum_sofar;
}
int better_method(int *arr, int n)
{
    int sum[n];
    sum[0] = arr[0];
    int max_sum = 0;
    for (int i = 1; i < n; i++)
    {
        sum[i] = arr[i] + sum[i - 1];
    }
    for (int i = 0; i < n; i++)
    {
        for (int j = i; j < n; j++)
        {
            int sum_temp = 0;
            if (i == 0)
            {
                sum_temp = sum[j];
            }
            else
            {
                sum_temp = sum[j] - sum[i - 1];
            }
            max_sum = max(max_sum, sum_temp);
        }
    }

    return max_sum;
}

int naive_method(int *arr, int n)
{
    int max_sum = 0;
    for (int i = 0; i < n; i++)
    {
        for (int j = i; j < n; j++)
        {

            int sum = 0;
            for (int k = i; k <= j; k++)
            {
                sum += arr[k];
            }
            max_sum = max(sum, max_sum);
        }
    }
    return max_sum;
}
int main()
{
    int testcases = 0;
    cin >> testcases;
    for (int i = 0; i < testcases; i++)
    {
        int arrCount = 0;
        cin >> arrCount;
        int arr[arrCount];
        for (int j = 0; j < arrCount; j++)
        {
            cin >> arr[j];
        }
        cout << better_method(arr, arrCount) << endl;
    }

    return 0;
}